name: Daily Run

on:
  schedule:
    - cron: '0 19 * * *'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3

      - name: Set up Go
        uses: actions/setup-go@v4  # Updated to v4
        with:
          go-version: '1.21'  # Updated to latest stable Go version

      - name: Run Go Script
        env:  # Add your environment variables here
          HASURA_ENDPOINT: ${{ secrets.HASURA_ENDPOINT }}
          HASURA_ADMIN_SECRET: ${{ secrets.HASURA_ADMIN_SECRET }}
        run: go run main.go

      - name: Check for changes and commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add products.xml
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update products.xml [skip ci]"
            git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
